### ISSUE TITLE
Behavior of 0-dimensional array

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#107]
Behavior of 0-dimensional array is strange.

```
>>> x = numpy.array(1)
>>> x
array(1)
>>> x + x
2
```

So, infix operators of `Variable` also have the same problem.

```
>>> x = chainer.Variable(numpy.array(1))
>>> x.data
array(1)
>>> y = x + x
>>> y.data
2
```

We have two choices:

- Forbid 0-dimensional array. Instead use 1-dimension array which has only one element.
- Check type of an array in `Function`s. When an array is converted to a scalar, we need to re-convert the value to 0-dimensional array.

This issue is related to #100

**Comment by unnonouno** [comment]
We are assuming that `Variable.data` is `ndarray` or `GPUArray`, but this problem breaks this assumption. (related to #101)

**Comment by kamikawa** [comment]
Hi

You may be able to use numpy.matrix instead of numpy.array.
numpy.matrix does not automatically change its data type as array does.

**Comment by beam2d** [comment]
Thank you for the suggestion. numpy.matrix is dedicated for two dimensional arrays. I think it's not suited as the basic array type of Chainer, since we sometimes have to use arrays with more than two dimensions (e.g. a batch of images has four dimensions). I think converting between numpy.matrix and numpy.array is as cumbersome as converting between scalars and numpy.array.

**Comment by kamikawa** [comment]
I  understand the situation. It  seems inappropriate to use matrix type. Please forget it.
