### ISSUE TITLE
failed to install chainer with cuda support

### ISSUE THREAD

**Issue by abcteo** [pfnet/chainer#1241]
Hi, i have cuda 7.5 installed, and tested with cuda sample.
when try to install chainer, cant not get cuda support even i already set all the path environments

/usr/bin/ld: cannot find -lcuda
    collect2: error: ld returned 1 exit status
    **************************************************
    **\* WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand']
    **\* WARNING: Skip installing cuda support
    **\* WARNING: Check your LIBRARY_PATH environment variable
    **************************************************
    Include directories: ['/usr/local/cuda-7.5/include']
    Library directories: ['/usr/local/cuda-7.5/lib64', '/usr/local/cuda-7.5/lib']

even i already have this in .bashrc
export LD_LIBRARY_PATH=${CUDA_PATH}/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda-7.5/lib64:$LIBRARY_PATH

would you please advice
Thank you

**Comment by unnonouno** [comment]
This error represents `ld` command failed to find these libraries.
Please teach me your environment about OS and python version.

How did you install CUDA? Using `.run` file, or `deb` file?

I suspect `libcuda.so`. Can you find it?

**Comment by tabetomo** [comment]
Possibly I encountered the similar problem in Mac OS X (El Capitan, 10.11.5) with Python 2.7.10 :: Anaconda 2.4.0 (x86_64) and CUDA being installed using the official dmg(local), cuda_7.5.27_mac.dmg.

It seemed the problem was resolved after I put the following in the bash shell 

  export LDFLAGS="-F/Library/Frameworks/" 

as suggested in http://stackoverflow.com/questions/22885913/clang-error-cuda-directory-not-found-on-osx-mavericks. The same "@rpath/CUDA.framework/Versions/A/CUDA" problem was also reported in http://stackoverflow.com/questions/11632919/cuda-programming-and-xcode
which may help understanding if someone with Mac has the similar problem.

### Details

pip install chainer --no-cache-dir -vvvv 

and I got the following error.

ld: file not found: @rpath/CUDA.framework/Versions/A/CUDA for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    **************************************************
    *** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your LIBRARY_PATH environment variable


## Note
Note: my chainer doesn't work yet when running chainer -g 0

That might be due to my mac mini doesn't have a NVIDIA graphic card but only has "Intel Iris 1536 **MB"... 

Anyway the followng was the message.

/Users/XXXX/.pyenv/versions/anaconda-2.4.0/lib/python2.7/site-packages/chainer/cuda.py:87: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'
Traceback (most recent call last):
  File "/Users/XXXX/home/python/chainer/examples/imagenet/train_imagenet.py", line 110, in <module>
    cuda.get_device(args.gpu).use()
  File "cupy/cuda/device.pyx", line 73, in cupy.cuda.device.Device.use (cupy/cuda/device.cpp:1804)
  File "cupy/cuda/device.pyx", line 79, in cupy.cuda.device.Device.use (cupy/cuda/device.cpp:1753)
  File "cupy/cuda/runtime.pyx", line 151, in cupy.cuda.runtime.setDevice (cupy/cuda/runtime.cpp:2428)
  File "cupy/cuda/runtime.pyx", line 110, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:1821)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version

## But it was really improved because the early message had been
Traceback (most recent call last):
  File "/Users/XXXX/home/python/chainer/examples/imagenet/train_imagenet.py", line 67, in <module>
    cuda.check_cuda_available()
  File "/Users/XXXX/.pyenv/versions/anaconda-2.4.0/lib/python2.7/site-packages/chainer/cuda.py", line 84, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.
