### ISSUE TITLE
Data-parallel computation on multiple GPUs requires update of learning rate

### ISSUE THREAD

**Issue by amitibo** [pfnet/chainer#1338]
Hi. I am experiment with data parallel strategy using multiple GPUs. I noticed that the gradients calculated on the different models/GPUs are summed. This increases the amplitude of the gradient. To compensate for this, I had to decrease the learning rate accordingly. Without this decrease the model parameters diverge (NaN). I am not sure that decreasing the learning rate is a general enough solution. It seems that instead of summing the gradients,  it is better to average them.

**Comment by delta2323** [comment]
Thank you for suggestion. I think accumulating the gradient from different model is appropriate because this behavior is similar to the situation where we use the single model (single GPU) and bundle all minibatches into one so that the number of data points used in one iteration is unchanged. The gradient of each parameter is the sum of the ones which we calculate with data points in the minibatch.

For example, if you use single model and multiply the number of data points in the minibatch by the number of model in the data parallel strategy, so that total number of data points in one iteration is same as the data parallel situation, I guess the parameter of models will diverge in that case, too.

Is my answer to the point?

**Comment by amitibo** [comment]
Hi. I think that running multiple GPU or accumulating gradients of a single model have the same effect. In both cases one would have to adjust the optimization parameters. I suggest to at least add a note to the user as done in the first paragraph of the caffe multi-gpu documentation: [https://github.com/BVLC/caffe/blob/master/docs/multigpu.md](url)

**Comment by delta2323** [comment]
@amitibo  Thank you for your suggestion. I made a PR reflecting your comment.
