### ISSUE TITLE
Inconsistent element-wise function behavior with multiple GPUs

### ISSUE THREAD

**Issue by psmaragdis** [pfnet/chainer#1403]
I have some code that produces an error when I use element-wise subtraction, but not when I use element-wise subtraction. Here is the code I used below:

```
# Simple test network
class test_t( chainer.Chain):
    # Initialize the network
    def __init__( self):
        super( test_t, self).__init__(
            l1 = L.Linear( 2, 2)
        )

    # Define the loss function
    def loss( self, x, y):
        
        # Select case to test
        case = 1

        # This doesn't work
        if case == 1:
            z = F.tanh( self.l1( x))
            d = z - y
            return F.sum( d*d)
        
        # This works
        elif case == 2:
            z = -F.tanh( self.l1( x))
            d = z + y
            return F.sum( d*d)


# Data to play with
x = random.randn( 1000, 2).astype( float32)

# Select the non-default GPU
GPU = 1

# Setup and get loss
model = test_t().to_gpu( GPU)
model.loss( 
    chainer.Variable( chainer.cuda.to_gpu( x, GPU)),
    chainer.cuda.to_gpu( x, GPU)
)
```

If you change the ``case`` variable to 1 it will use an element-wise subtraction to compute the loss. In this case I get an error that ``Array device must be same as the current device: array device = 1 while current = 0``. If I change ``case`` to 2 it negates one of the operants and then uses element-wise addition to compute the same thing as before. In this case there is no error.

In this case there is an easy workaround, but this also happens when I use LSTM layers and it doesn't feel right to go in the LSTM function and start changing signs.

**Comment by delta2323** [comment]
Hi

Thank you for reporting the issue. The solution is to switches the current device as follows:

```
        if case == 1:
            with chainer.cuda.get_device(y):
                z = F.tanh( self.l1( x))
                d = z - y
                return F.sum( d*d)
```

I describe of the reason of this behavior in detail. Please read it if you are interested in the internal of Chainer.

The problem comes from the difference of the negate operation of `chainer.Variable` and `cupy.ndarray`.

```
import chainer
import cupy
import numpy

cupy.cuda.Device(0).use
with cupy.cuda.Device(1):
    data = numpy.random.randn(1000, 2).astype(numpy.float32)

-chainer.Variable(x)  # (1) OK
-x  # (2) Error
```

(1) invokes `F.Neg.forward` is invoked through `Chainer.Function.__call__`. When `Function.__call__` is invoked, Chainer automatically switches the current device to the one which the input data are located (you can check the behavior [here](https://github.com/pfnet/chainer/blob/master/chainer/function.py#L129)).

On the other hand, in (2),  only `cupy.ndarray.__neg__` is invokded and does not switch the device. If the device the data is located is different from current device, the error is raised.

In your case, negation in `-F.tanh(self.)` in case 2 implicitly calls `F.Neg.forward`. Contrary to that, `z - y` is equivalent to `F.AddConstant(-rhs)(lhs)` where `rhs` is `y` and `lhs` is `z`. So `cupy.ndarray.__neg__` is called *before* `F.AddConstant.__call__` is invoked and device inconsistency happens.

**Comment by psmaragdis** [comment]
Thanks for the detailed explanation, that makes sense.  My main frustration was that when I use x+y, x-y, x*y or x/y I get different behavior (- and / give errors, + and * don't) which is somewhat unexpected.
