### ISSUE TITLE
Bug in train_ptb.py

### ISSUE THREAD

**Issue by tasmalinakis** [pfnet/chainer#336]
Hello, I think that the indices i and j should be reversed in the learning loop (lines 119 and 121). As is right now, the text is not parsed in continuous order.

**Comment by beam2d** [comment]
Thank you for the suggestion, though I think the current code is correct. This is a bit confusing case.

In this example, RNN runs through `batchsize` sequences in parallel. These sequences are coming from one long sequence, where the offsets are different; the `j`-th sequence starts from the `jump * j`-th word. In order to leverage the minibatch computation, the current and its next word of each sequence are packed into the minibatch arrays in these two lines. Note that `i` indicates the index of the current word for all sequences. Thus, the index of the `i`-th word of the `j`-th sequence is `jump * j + i`.
