### ISSUE TITLE
Function may raise CUDNN_STATUS_BAD_PARAM when CPU/GPU mismatch

### ISSUE THREAD

**Issue by sinhrks** [pfnet/chainer#787]
When cuDNN is available, ``spatial_pyramid_pooling_2d`` raises following error when function is on CPU and passed ``Variable`` is on GPU. Can this error to be more understandable?

```
# GPU
arr = np.random.randn(5, 3, 5, 5)
v = Variable(arr)
v.to_gpu()

F.spatial_pyramid_pooling_2d(v, 3, F.MaxPooling2D)
# cupy/cuda/cudnn.pyx in cupy.cuda.cudnn.poolingForward (cupy/cuda/cudnn.cpp:6127)()
# cupy/cuda/cudnn.pyx in cupy.cuda.cudnn.poolingForward (cupy/cuda/cudnn.cpp:5978)()
# cupy/cuda/cudnn.pyx in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1308)()
# CuDNNError: CUDNN_STATUS_BAD_PARAM: CUDNN_STATUS_BAD_PARAM
```

**Comment by okuta** [comment]
Please write test.

**Comment by delta2323** [comment]
I think this error is not caused by inconsistency between CPU and GPU because `spatial_pyramid_pooling_2d` does call cuDNN (and it fails).

When I change the dtype of `arr` to float32 by `arr = np.random.randn(5, 3, 5, 5).astype(np.float32)`, error does not occur. So we should check the dtype of inputs passed to cuDNN.

**Comment by delta2323** [comment]
I fix the code that would solve the problem.
