### ISSUE TITLE
Same api for GRU and LSTM 

### ISSUE THREAD

**Issue by benob** [pfnet/chainer#789]
Currently, GRU is stateless while LSTM is stateful. It would be great to make GRU stateful as well, for the stake of consistency.

**Comment by delta2323** [comment]
Thank you for suggestion. Just to be sure, do you agree with the idea that `links.LSTM` is stateful in the sense that it holds state (`self.h` and `self.c`) as attribute whereas `functions.LSTM` and `links.GRU` are stateless because they take current state (`h` and `c` for `LSTM` and `h` for `GPU`) as inputs and do not hold them as attributes?

One of the suggestion is, like LSTM, to make `links.GPU` stateful and `functions.GPU` stateless.

**Comment by benob** [comment]
Yes, this is what I mean.

**Comment by delta2323** [comment]
I see. I agree with your suggestion.
